/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    articles: Article;
    'faq-groups': FaqGroup;
    'manual-chapters': ManualChapter;
    'known-bugs': KnownBug;
    'open-questions': OpenQuestion;
    'bug-reports': BugReport;
    'question-submissions': QuestionSubmission;
    roadmap: Roadmap;
    'cockpit-daily': CockpitDaily;
    'health-checks': HealthCheck;
    'patris-entitlements': PatrisEntitlement;
    media: Media;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    articles: ArticlesSelect<false> | ArticlesSelect<true>;
    'faq-groups': FaqGroupsSelect<false> | FaqGroupsSelect<true>;
    'manual-chapters': ManualChaptersSelect<false> | ManualChaptersSelect<true>;
    'known-bugs': KnownBugsSelect<false> | KnownBugsSelect<true>;
    'open-questions': OpenQuestionsSelect<false> | OpenQuestionsSelect<true>;
    'bug-reports': BugReportsSelect<false> | BugReportsSelect<true>;
    'question-submissions': QuestionSubmissionsSelect<false> | QuestionSubmissionsSelect<true>;
    roadmap: RoadmapSelect<false> | RoadmapSelect<true>;
    'cockpit-daily': CockpitDailySelect<false> | CockpitDailySelect<true>;
    'health-checks': HealthChecksSelect<false> | HealthChecksSelect<true>;
    'patris-entitlements': PatrisEntitlementsSelect<false> | PatrisEntitlementsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'kundencheck-hinweise': KundencheckHinweise;
    'patris-import': PatrisImport;
  };
  globalsSelect: {
    'kundencheck-hinweise': KundencheckHinweiseSelect<false> | KundencheckHinweiseSelect<true>;
    'patris-import': PatrisImportSelect<false> | PatrisImportSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles".
 */
export interface Article {
  id: number;
  slug: string;
  category: 'Verbindungssuche' | 'Konto & Personalisierung' | 'Fahrplanauskunft' | 'Tickets' | 'Hilfe & Kontakt';
  title: string;
  excerpt?: string | null;
  meta?: string | null;
  short?: string | null;
  steps?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  stepGroups?:
    | {
        heading: string;
        items?:
          | {
              text: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  tips?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  related?: (number | Article)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faq-groups".
 */
export interface FaqGroup {
  id: number;
  group: string;
  order?: number | null;
  items?:
    | {
        q: string;
        a: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "manual-chapters".
 */
export interface ManualChapter {
  id: number;
  slug: string;
  order?: number | null;
  num?: string | null;
  title: string;
  layout?: ('single' | 'row') | null;
  reverse?: boolean | null;
  images?: (number | Media)[] | null;
  paras?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  bullets?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  note?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "known-bugs".
 */
export interface KnownBug {
  id: number;
  bugId: string;
  /**
   * „Gemeldet“ und „Offen“ stehen oben (nach Priorität), „Behoben“ erscheint unten.
   */
  state: 'gemeldet' | 'offen' | 'behoben';
  /**
   * Blendet den Fehler öffentlich aus, ohne ihn zu löschen. Jederzeit umkehrbar.
   */
  hidden?: boolean | null;
  severity: 'hoch' | 'mittel' | 'niedrig';
  title: string;
  fundort?: string | null;
  description?: string | null;
  steps?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  expected?: string | null;
  actual?: string | null;
  images?: (number | Media)[] | null;
  caption?: string | null;
  noImageNote?: string | null;
  reverse?: boolean | null;
  builtin?: boolean | null;
  /**
   * Wird automatisch gefüllt, sobald der Status auf „Gemeldet“ steht und Jira konfiguriert ist. Verhindert doppelte Tickets.
   */
  jiraKey?: string | null;
  /**
   * Direktlink zum angelegten Jira-Vorgang.
   */
  jiraUrl?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "open-questions".
 */
export interface OpenQuestion {
  id: number;
  group: string;
  order?: number | null;
  items?:
    | {
        qid: string;
        status: 'offen' | 'beantwortet';
        question: string;
        answer?: string | null;
        note?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Von Nutzenden über das öffentliche Formular gemeldete Fehler. Nach Prüfung ggf. als „Bekannter Fehler“ übernehmen und hier den Status setzen.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bug-reports".
 */
export interface BugReport {
  id: number;
  status: 'neu' | 'in-pruefung' | 'uebernommen' | 'abgelehnt';
  severity: 'hoch' | 'mittel' | 'niedrig';
  title: string;
  description: string;
  steps?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  expected?: string | null;
  actual?: string | null;
  reporter?: string | null;
  images?: (number | Media)[] | null;
  internalNote?: string | null;
  /**
   * Wird automatisch gesetzt, sobald der Status auf „Übernommen“ gestellt und gespeichert wird.
   */
  convertedTo?: (number | null) | KnownBug;
  updatedAt: string;
  createdAt: string;
}
/**
 * Von Nutzenden über das öffentliche Formular eingereichte Fragen. Antwort ergänzen, Zielgruppe wählen und Status auf „Übernommen“ setzen, damit die Frage online erscheint.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "question-submissions".
 */
export interface QuestionSubmission {
  id: number;
  status: 'neu' | 'in-pruefung' | 'uebernommen' | 'abgelehnt';
  /**
   * In welcher Gruppe die Frage nach Übernahme erscheint. Leer = „Von Nutzenden eingereicht“.
   */
  targetGroup?: (number | null) | OpenQuestion;
  question: string;
  answer?: string | null;
  reporter?: string | null;
  /**
   * E-Mail oder Telefon, falls die Person eine Antwort wünscht.
   */
  contact?: string | null;
  internalNote?: string | null;
  /**
   * Wird automatisch gesetzt, sobald die Frage übernommen wurde.
   */
  convertedTo?: (number | null) | OpenQuestion;
  publishedQid?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Inhalte der Seite „Ausblick auf Version 2“. Blöcke lassen sich hinzufügen, sortieren und mit Punkten füllen.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "roadmap".
 */
export interface Roadmap {
  id: number;
  /**
   * Kleinere Zahl = weiter oben.
   */
  order?: number | null;
  kicker?: string | null;
  heading: string;
  intro?: string | null;
  items?:
    | {
        title: string;
        status: 'geplant' | 'in Prüfung' | 'in Vorbereitung';
        text?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Automatisch befüllte Tages-Aggregate für die Migrations-Zeitreihe.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cockpit-daily".
 */
export interface CockpitDaily {
  id: number;
  /**
   * Format JJJJ-MM-TT.
   */
  datum: string;
  logins: number;
  loginErrors: number;
  newUsers: number;
  registrations: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * Minütliche Systemstatus-Checks (Ampel, Alerting, Verfügbarkeit).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "health-checks".
 */
export interface HealthCheck {
  id: number;
  checkedAt: string;
  status?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  failCounts?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  alertedDown?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Ticketberechtigungen aus dem Patris-Export. Befüllung ausschließlich per CSV-Upload im Migrations-Cockpit (ersetzt den gesamten Bestand).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "patris-entitlements".
 */
export interface PatrisEntitlement {
  id: number;
  entitlementId: string;
  validFrom?: string | null;
  validUntil?: string | null;
  productNumber?: string | null;
  productName?: string | null;
  customerNumber?: string | null;
  email?: string | null;
  firstName?: string | null;
  lastName?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  /**
   * Bei neuen Fehlermeldungen und eingereichten Fragen eine E-Mail erhalten. Kann jederzeit deaktiviert werden.
   */
  notifyOnSubmissions?: boolean | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'articles';
        value: number | Article;
      } | null)
    | ({
        relationTo: 'faq-groups';
        value: number | FaqGroup;
      } | null)
    | ({
        relationTo: 'manual-chapters';
        value: number | ManualChapter;
      } | null)
    | ({
        relationTo: 'known-bugs';
        value: number | KnownBug;
      } | null)
    | ({
        relationTo: 'open-questions';
        value: number | OpenQuestion;
      } | null)
    | ({
        relationTo: 'bug-reports';
        value: number | BugReport;
      } | null)
    | ({
        relationTo: 'question-submissions';
        value: number | QuestionSubmission;
      } | null)
    | ({
        relationTo: 'roadmap';
        value: number | Roadmap;
      } | null)
    | ({
        relationTo: 'cockpit-daily';
        value: number | CockpitDaily;
      } | null)
    | ({
        relationTo: 'health-checks';
        value: number | HealthCheck;
      } | null)
    | ({
        relationTo: 'patris-entitlements';
        value: number | PatrisEntitlement;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles_select".
 */
export interface ArticlesSelect<T extends boolean = true> {
  slug?: T;
  category?: T;
  title?: T;
  excerpt?: T;
  meta?: T;
  short?: T;
  steps?:
    | T
    | {
        text?: T;
        id?: T;
      };
  stepGroups?:
    | T
    | {
        heading?: T;
        items?:
          | T
          | {
              text?: T;
              id?: T;
            };
        id?: T;
      };
  tips?:
    | T
    | {
        text?: T;
        id?: T;
      };
  related?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faq-groups_select".
 */
export interface FaqGroupsSelect<T extends boolean = true> {
  group?: T;
  order?: T;
  items?:
    | T
    | {
        q?: T;
        a?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "manual-chapters_select".
 */
export interface ManualChaptersSelect<T extends boolean = true> {
  slug?: T;
  order?: T;
  num?: T;
  title?: T;
  layout?: T;
  reverse?: T;
  images?: T;
  paras?:
    | T
    | {
        text?: T;
        id?: T;
      };
  bullets?:
    | T
    | {
        text?: T;
        id?: T;
      };
  note?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "known-bugs_select".
 */
export interface KnownBugsSelect<T extends boolean = true> {
  bugId?: T;
  state?: T;
  hidden?: T;
  severity?: T;
  title?: T;
  fundort?: T;
  description?: T;
  steps?:
    | T
    | {
        text?: T;
        id?: T;
      };
  expected?: T;
  actual?: T;
  images?: T;
  caption?: T;
  noImageNote?: T;
  reverse?: T;
  builtin?: T;
  jiraKey?: T;
  jiraUrl?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "open-questions_select".
 */
export interface OpenQuestionsSelect<T extends boolean = true> {
  group?: T;
  order?: T;
  items?:
    | T
    | {
        qid?: T;
        status?: T;
        question?: T;
        answer?: T;
        note?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bug-reports_select".
 */
export interface BugReportsSelect<T extends boolean = true> {
  status?: T;
  severity?: T;
  title?: T;
  description?: T;
  steps?:
    | T
    | {
        text?: T;
        id?: T;
      };
  expected?: T;
  actual?: T;
  reporter?: T;
  images?: T;
  internalNote?: T;
  convertedTo?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "question-submissions_select".
 */
export interface QuestionSubmissionsSelect<T extends boolean = true> {
  status?: T;
  targetGroup?: T;
  question?: T;
  answer?: T;
  reporter?: T;
  contact?: T;
  internalNote?: T;
  convertedTo?: T;
  publishedQid?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "roadmap_select".
 */
export interface RoadmapSelect<T extends boolean = true> {
  order?: T;
  kicker?: T;
  heading?: T;
  intro?: T;
  items?:
    | T
    | {
        title?: T;
        status?: T;
        text?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cockpit-daily_select".
 */
export interface CockpitDailySelect<T extends boolean = true> {
  datum?: T;
  logins?: T;
  loginErrors?: T;
  newUsers?: T;
  registrations?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "health-checks_select".
 */
export interface HealthChecksSelect<T extends boolean = true> {
  checkedAt?: T;
  status?: T;
  failCounts?: T;
  alertedDown?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "patris-entitlements_select".
 */
export interface PatrisEntitlementsSelect<T extends boolean = true> {
  entitlementId?: T;
  validFrom?: T;
  validUntil?: T;
  productNumber?: T;
  productName?: T;
  customerNumber?: T;
  email?: T;
  firstName?: T;
  lastName?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  notifyOnSubmissions?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Texte, die der Kundencheck je Situation anzeigt. Platzhalter: {produkt}, {von}, {bis}, {vorname}, {nachname}, {kundennummer} (Patris) sowie {kaufdatum}, {kaufprodukt}, {bestellnummer} (letzter erfolgreicher Kauf in der App).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "kundencheck-hinweise".
 */
export interface KundencheckHinweise {
  id: number;
  /**
   * Laut Patris ist heute ein Ticket gültig, es gibt ein Keycloak-Konto und in der App wurde kürzlich ein Ticket ausgeliefert (oder die Kaufdaten sind nicht abrufbar).
   */
  aktivMitKonto?: {
    titel?: string | null;
    text?: string | null;
  };
  /**
   * Laut Patris ist heute ein Ticket gültig und es gibt ein Konto, in der App wurde in den letzten 35 Tagen aber kein Ticket erfolgreich ausgeliefert.
   */
  aktivOhneKauf?: {
    titel?: string | null;
    text?: string | null;
  };
  /**
   * Laut Patris ist heute ein Ticket gültig, in Keycloak gibt es aber noch kein Konto.
   */
  aktivOhneKonto?: {
    titel?: string | null;
    text?: string | null;
  };
  /**
   * Laut Patris ist ein Ticket vorgesehen, dessen Gültigkeit noch nicht begonnen hat.
   */
  zukuenftig?: {
    titel?: string | null;
    text?: string | null;
  };
  /**
   * Laut Patris gibt es nur Tickets, deren Gültigkeit bereits abgelaufen ist.
   */
  abgelaufen?: {
    titel?: string | null;
    text?: string | null;
  };
  /**
   * Zur E-Mail-Adresse bzw. Kundennummer gibt es in den Patris-Daten keinen Eintrag.
   */
  keinTicket?: {
    titel?: string | null;
    text?: string | null;
  };
  /**
   * Laut Patris ist aktuell kein Ticket vorgesehen (oder es liegen keine Patris-Daten vor), in der App wurde aber in den letzten 35 Tagen ein Ticket erfolgreich ausgeliefert.
   */
  appKauf?: {
    titel?: string | null;
    text?: string | null;
  };
  /**
   * Im Migrations-Cockpit wurde noch keine Patris-CSV hochgeladen.
   */
  keineDaten?: {
    titel?: string | null;
    text?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Letzter CSV-Upload der Patris-Ticketdaten (Upload im Migrations-Cockpit).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "patris-import".
 */
export interface PatrisImport {
  id: number;
  importedAt?: string | null;
  fileName?: string | null;
  importedBy?: string | null;
  rowCount?: number | null;
  skippedRows?: number | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "kundencheck-hinweise_select".
 */
export interface KundencheckHinweiseSelect<T extends boolean = true> {
  aktivMitKonto?:
    | T
    | {
        titel?: T;
        text?: T;
      };
  aktivOhneKauf?:
    | T
    | {
        titel?: T;
        text?: T;
      };
  aktivOhneKonto?:
    | T
    | {
        titel?: T;
        text?: T;
      };
  zukuenftig?:
    | T
    | {
        titel?: T;
        text?: T;
      };
  abgelaufen?:
    | T
    | {
        titel?: T;
        text?: T;
      };
  keinTicket?:
    | T
    | {
        titel?: T;
        text?: T;
      };
  appKauf?:
    | T
    | {
        titel?: T;
        text?: T;
      };
  keineDaten?:
    | T
    | {
        titel?: T;
        text?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "patris-import_select".
 */
export interface PatrisImportSelect<T extends boolean = true> {
  importedAt?: T;
  fileName?: T;
  importedBy?: T;
  rowCount?: T;
  skippedRows?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}